### ISSUE TITLE
[vite] Internal server error: Cannot overwrite across a split point

### ISSUE THREAD

**Issue by Dids** [facing-dev/vue-facing-decorator#14]
Using Vue 3 + SFC + TypeScript + Vite, and I consistently get this error whenever I try to use either the now "deprecated" `vue-class-component` or this library (`vue-facing-decorator`), which I've been using now, in hopes of fixing this.  
I'm using pretty much latest stable versions of everything, but have tried rolling back several versions, except it makes no difference.  
Additionally, I'm on macOS + M1 Pro (arm64/aarc64), just in case that makes a difference.

So far I've been entirely unable to track down why this happens, and it only seems to happen in larger components, while smaller components seem to be fine, but I'll keep digging, removing code piece by piece, until it stops and see if I can track it down.  
In the meantime, I just wanted to ask around to see if anyone else has ran into this, as Google is not returning any useful results for this particular error.

Here's the full error:
```
[vite] Internal server error: Cannot overwrite across a split point
  Plugin: vite:vue
  File: /Users/dids/Work/Other/presentor-backend-frontend/src/components/TableV2/TableV2.vue
      at MagicString.overwrite (/Users/dids/Work/Other/presentor-backend-frontend/node_modules/magic-string/dist/magic-string.cjs.js:693:11)
      at /Users/dids/Work/Other/presentor-backend-frontend/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3355:15
      at Array.forEach (<anonymous>)
      at Object.rewriteDefault (/Users/dids/Work/Other/presentor-backend-frontend/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3353:9)
      at genScriptCode (/Users/dids/Work/Other/presentor-backend-frontend/node_modules/@vitejs/plugin-vue/dist/index.cjs:2231:37)
      at transformMain (/Users/dids/Work/Other/presentor-backend-frontend/node_modules/@vitejs/plugin-vue/dist/index.cjs:2111:54)
      at TransformContext.transform (/Users/dids/Work/Other/presentor-backend-frontend/node_modules/@vitejs/plugin-vue/dist/index.cjs:2499:16)
      at Object.transform (file:///Users/dids/Work/Other/presentor-backend-frontend/node_modules/vite/dist/node/chunks/dep-561c5231.js:35252:53)
      at async loadAndTransform (file:///Users/dids/Work/Other/presentor-backend-frontend/node_modules/vite/dist/node/chunks/dep-561c5231.js:39740:29)
```

**Comment by ruojianll** [comment]
So far, I don't suffer the error and know nothing about it. But after reading the error stack, I think vue use magic-string to compile SFC file and throw the error during compiling time. So everywhere of the whole SFC file content may cause the error.

If everything is fine while you don't using any decorator libraries, it should happened in type script code section. Try to separate ts code to a single file and import it, see if the error fixed.

```
// MyComponent.class.ts
...
@Component
export default MyComponent extends Vue{
}

//MyComponent.vue
<template></template>
<style></style>
<script lang="ts">
import MyComponent from './MyComponent.class.ts"
export default MyComponent
</script>
```

Due to the component class code is loaded from a ts file, SFC compiler will skip it maybe.

**Comment by ruojianll** [comment]
I advice you to contribute the issue to `@vue/compiler-sfc` team.

**Comment by Dids** [comment]
Thank you, I had a feeling but wanted to confirm first. :)

I'll close this issue and see if I can dig up more information and/or a reproducible example and post a new issue to the Vue/SFC repository.

**Comment by ruojianll** [comment]
If you create an issue about this, please @me. thank you.

**Comment by ruojianll** [comment]
Congratulations! It seems to work fine on all decorator repos.
